version: 2.1

orbs:
  docker: circleci/docker@1.4.0
  windows: circleci/windows@2.4.0

jobs:
  build-android-release:
    machine: true
    steps:
      - docker/pull:
        images: antiagainst/uvkcompute-ci:latest
      - checkout
      - run:
          name: Cross compile towards Android
          command: |
            docker run \
              --volume=$PWD:/usr/src/uVkCompute \
              --workdir=/usr/src/uVkCompute \
              --rm \
              antiagainst/uvkcompute-ci:latest \
              tools/ci/build_android.sh
  build-linux-debug:
    machine: true
    steps:
      - docker/pull:
        images: antiagainst/uvkcompute-ci:latest
      - checkout
      - run:
          name: Debug build on Linux
          command: |
            docker run \
              --volume=$PWD:/usr/src/uVkCompute \
              --workdir=/usr/src/uVkCompute \
              --rm \
              antiagainst/uvkcompute-ci:latest \
              tools/ci/build_linux.sh Debug
  build-linux-release:
    machine: true
    steps:
      - docker/pull:
        images: antiagainst/uvkcompute-ci:latest
      - checkout
      - run:
          name: Release build on Linux
          command: |
            docker run \
              --volume=$PWD:/usr/src/uVkCompute \
              --workdir=/usr/src/uVkCompute \
              --rm \
              antiagainst/uvkcompute-ci:latest \
              tools/ci/build_linux.sh Release
  build-windows-release:
    executor: windows/default
    steps:
      - run:
          name: Install build toolchain
          shell: cmd.exe
          command: cinst cmake vulkan-sdk
      - checkout
      - run:
          name: Update submodules
          shell: cmd.exe
          command: git submodule update --init
      - run:
          name: Release build on Windows
          shell: powershell.exe
          command: tools/ci/build_windows.ps1

workflows:
  build-android:
    jobs:
      - build-android-release
  build-linux:
    jobs:
      - build-linux-debug
      - build-linux-release
  build-windows:
    jobs:
      - build-windows-release
